services:
  # Servicio de la base de datos para Airflow
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - mlops-network
    restart: unless-stopped

  # Servicio del servidor web de Airflow
  airflow-webserver:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    hostname: airflow-webserver
    command: ["webserver"]
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__RBAC=true
      - AIRFLOW__WEBSERVER__ENABLE_CORS=true
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./mlruns:/mlruns
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mlops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Servicio del scheduler de Airflow
  airflow-scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    hostname: airflow-scheduler
    command: ["scheduler"]
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./mlruns:/mlruns
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    networks:
      - mlops-network
    restart: unless-stopped

  # Servicio de MLflow UI
  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-ui
    command: mlflow ui --backend-store-uri file:/mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - mlops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:

networks:
  mlops-network:
    driver: bridge